# Generated by Django 4.0.1 on 2022-02-08 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_username_sinup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinup',
            name='name',
        ),
    ]
